server:
  port: ${MY_API_PORT:8082}

spring:
  application:
    name: "test_prueba_setic_2"
  r2dbc:
    url: r2dbc:mysql://${MY_API_DB_HOST:localhost}:${MY_API_DB_PORT:3306}/${MY_API_DB_NAME:franquicia}?useSSL=false
    username: ${MY_API_DB_USER:root}
    password: ${MY_API_DB_PASSWORD:1234}
  sql:
    init:
      mode: always
      
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
